using System.IO;
using NUnit.Framework;
using osu.Game.Rulesets.BmsRuleset.UI.HudComponents.Bga;
using osu.Game.Rulesets.BmsRuleset.Media.FFmpeg;

namespace osu.Game.Rulesets.BmsRuleset.Tests.Normal.Bga;

[TestFixture]
public class BmsBgaVideoFactoryTest
{
    // Routing is codec-driven, not extension-driven: the supplemental provider probes each
    // file's video codec via the FFmpeg backend and claims only files whose codec the backend
    // ships a decoder for. wmv2 stays with the framework (it has a wmv2 decoder; the supplemental
    // build intentionally omits it), and .avi is split by codec (cinepak → supplemental, mpeg4 →
    // framework). Fixtures are 5-frame clips generated by ffmpeg.

    private static string fixturePath(string name) =>
        Path.Combine(TestContext.CurrentContext.TestDirectory, "bga_fixtures", name);

    [TestCase("mpeg1.mpg", Description = "Legacy MPEG-1 — supplemental owns (framework lacks the decoder)")]
    public void TestLegacyMpegRoutesToSupplemental(string fixture)
    {
        if (!BmsSupplementalFFmpegFuncs.IsAvailable)
            Assert.Ignore("Supplemental FFmpeg backend is not embedded in this build.");

        Assert.That(BmsBgaVideoFactory.SelectProviderName(fixturePath(fixture)), Is.EqualTo("supplemental-ffmpeg"));
    }

    [TestCase("wmv1.wmv", Description = "WMV family the framework can't decode — claimed by codec probe, not extension")]
    public void TestWmvFamilyRoutesToSupplementalByCodec(string fixture)
    {
        if (!BmsSupplementalFFmpegFuncs.IsAvailable)
            Assert.Ignore("Supplemental FFmpeg backend is not embedded in this build.");

        Assert.That(BmsBgaVideoFactory.SelectProviderName(fixturePath(fixture)), Is.EqualTo("supplemental-ffmpeg"));
    }

    [TestCase("cinepak.avi", Description = ".avi is codec-ambiguous — cinepak goes to supplemental, not framework")]
    public void TestAviLegacyCodecRoutesToSupplemental(string fixture)
    {
        if (!BmsSupplementalFFmpegFuncs.IsAvailable)
            Assert.Ignore("Supplemental FFmpeg backend is not embedded in this build.");

        Assert.That(BmsBgaVideoFactory.SelectProviderName(fixturePath(fixture)), Is.EqualTo("supplemental-ffmpeg"));
    }

    [Test(Description = "wmv2: framework ships a decoder, so the supplemental probe must decline it")]
    public void TestWmv2StaysWithFramework()
    {
        if (!BmsSupplementalFFmpegFuncs.IsAvailable)
            Assert.Ignore("Supplemental FFmpeg backend is not embedded in this build.");

        Assert.That(BmsBgaVideoFactory.SelectProviderName(fixturePath("wmv2.wmv")), Is.EqualTo("framework"));
    }

    [TestCase("h264.mp4", Description = "Modern container the supplemental build can't demux — framework handles")]
    [TestCase("mpeg4.avi", Description = ".avi with a codec the supplemental build lacks — framework handles")]
    public void TestModernRoutesToFramework(string fixture)
    {
        // No IsAvailable gate: supplemental declines these by extension pre-filter (mp4) or by
        // probe (mpeg4 in avi) whether or not the backend is embedded, so framework always wins.
        Assert.That(BmsBgaVideoFactory.SelectProviderName(fixturePath(fixture)), Is.EqualTo("framework"));
    }

    [Test(Description = "Without the native backend, supplemental declines and .mpg falls to missing (framework can't decode pure MPEG either)")]
    public void TestMpegFallsToMissingWhenSupplementalUnavailable()
    {
        if (BmsSupplementalFFmpegFuncs.IsAvailable)
            Assert.Ignore("Supplemental FFmpeg backend is embedded in this build.");

        Assert.That(BmsBgaVideoFactory.SelectProviderName(fixturePath("mpeg1.mpg")), Is.EqualTo("missing"));
    }
}
