<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup Label="Project">
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyTitle>osu.Game.Rulesets.BmsRuleset</AssemblyTitle>
        <OutputType>Library</OutputType>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <RootNamespace>osu.Game.Rulesets.BmsRuleset</RootNamespace>
        <Nullable>enable</Nullable>
        <Version>2026.621.2</Version>
        <LangVersion>14</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\**" WithCulture="false"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="ppy.osu.Game" Version="2026.621.0"/>
        <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0"/>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="osu.Game.Rulesets.BmsRuleset.Tests"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference
            Include="..\osu.Game.Rulesets.BmsRuleset.SourceGeneration\osu.Game.Rulesets.BmsRuleset.SourceGeneration.csproj"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>
