using System.Linq;
using NUnit.Framework;
using osu.Game.Rulesets.BmsRuleset.Beatmaps;
using osu.Game.Rulesets.BmsRuleset.BmsParser;
using osu.Game.Rulesets.BmsRuleset.Mods;
using osu.Game.Rulesets.BmsRuleset.Objects;

namespace osu.Game.Rulesets.BmsRuleset.Tests.Normal.Mods;

[TestFixture]
public class BmsModRotationRandomTest
{
    private const int total_columns = 8;

    private void applyMod(BmsModRotationRandom mod, BmsBeatmap beatmap)
    {
        mod.ApplyToBeatmap(beatmap);
    }

    private BmsBeatmap createBeatmap(params int[] columns)
    {
        var beatmap = new BmsBeatmap
        {
            LayoutVariant = BmsLayoutVariant.Bme7K,
            TotalColumns = total_columns,
        };

        for (var i = 0; i < columns.Length; i++)
        {
            beatmap.HitObjects.Add(new BmsHitObject
            {
                StartTime = 1000 + i * 125,
                Column = columns[i],
            });
        }

        return beatmap;
    }

    [Test]
    public void TestSeedDeterminism()
    {
        var beatmap1 = createBeatmap(0, 1, 2, 3, 4, 5, 6, 7);
        var beatmap2 = createBeatmap(0, 1, 2, 3, 4, 5, 6, 7);

        var mod1 = new BmsModRotationRandom { Seed = { Value = 42 } };
        var mod2 = new BmsModRotationRandom { Seed = { Value = 42 } };

        applyMod(mod1, beatmap1);
        applyMod(mod2, beatmap2);

        Assert.That(beatmap1.HitObjects.Select(h => h.Column),
            Is.EqualTo(beatmap2.HitObjects.Select(h => h.Column)));
    }

    [Test]
    public void TestResultIsBijectionWithScratch()
    {
        var beatmap = createBeatmap(0, 1, 2, 3, 4, 5, 6, 7);
        var mod = new BmsModRotationRandom { IncludeScratch = { Value = true }, Seed = { Value = 42 } };

        applyMod(mod, beatmap);

        var output = beatmap.HitObjects.Select(h => h.Column).ToArray();
        Assert.That(output.OrderBy(c => c), Is.EqualTo(Enumerable.Range(0, 8).ToArray()));
        Assert.That(isContinuousRotation(output), Is.True,
            "Mapping must be a continuous rotation when IncludeScratch=true");
    }

    [Test]
    public void TestScratchExcludedByDefault()
    {
        var beatmap = createBeatmap(0, 1, 2, 3, 4, 5, 6, 7);
        var mod = new BmsModRotationRandom { Seed = { Value = 42 } };

        applyMod(mod, beatmap);

        // Scratch stays at 0.
        Assert.That(beatmap.HitObjects[0].Column, Is.EqualTo(0));

        // Non-scratch columns are mapped in their original order (not sorted).
        var nonScratch = beatmap.HitObjects.Skip(1).Select(h => h.Column).ToArray();

        // Must be a continuous rotation: either ascending (normal base) or descending (mirror base).
        Assert.That(isContinuousRotation(nonScratch), Is.True,
            "Non-scratch mapping must be a continuous rotation (ascending or descending)");
    }

    /// <summary>Checks that <paramref name="values"/> is a cyclic shift of an ascending
    /// or descending sequence.</summary>
    private static bool isContinuousRotation(int[] values)
    {
        if (values.Length < 2) return true;

        // Check ascending rotation: each step is +1, wrapping max→min.
        bool ascending = true;
        for (int i = 0; i < values.Length; i++)
        {
            int cur = values[i];
            int next = values[(i + 1) % values.Length];
            int diff = next - cur;
            if (!(diff == 1 || (cur == values.Max() && next == values.Min())))
            {
                ascending = false;
                break;
            }
        }

        if (ascending) return true;

        // Check descending rotation: each step is -1, wrapping min→max.
        bool descending = true;
        for (int i = 0; i < values.Length; i++)
        {
            int cur = values[i];
            int next = values[(i + 1) % values.Length];
            int diff = next - cur;
            if (!(diff == -1 || (cur == values.Min() && next == values.Max())))
            {
                descending = false;
                break;
            }
        }

        return descending;
    }

    [Test]
    public void TestModAcronym()
    {
        Assert.That(new BmsModRotationRandom().Acronym, Is.EqualTo("RR"));
    }

    [Test]
    public void TestIncompatibleWithOtherMods()
    {
        var mod = new BmsModRotationRandom();
        Assert.That(mod.IncompatibleMods, Does.Contain(typeof(BmsModLaneRandom)));
        Assert.That(mod.IncompatibleMods, Does.Contain(typeof(BmsModNoteRandom)));
        Assert.That(mod.IncompatibleMods, Does.Contain(typeof(BmsModMirror)));
    }

    [Test]
    public void TestSeedAutoGenerated()
    {
        var mod = new BmsModRotationRandom();
        var beatmap = createBeatmap(0, 1);

        Assert.That(mod.Seed.Value, Is.Null);
        applyMod(mod, beatmap);
        Assert.That(mod.Seed.Value, Is.Not.Null);
    }

    [Test]
    public void TestNeverIdentity([Random(1, 100, 20)] int seed)
    {
        var beatmap = createBeatmap(0, 1, 2, 3, 4, 5, 6, 7);
        var mod = new BmsModRotationRandom { IncludeScratch = { Value = true }, Seed = { Value = seed } };

        applyMod(mod, beatmap);

        var output = beatmap.HitObjects.Select(h => h.Column).ToArray();
        Assert.That(output, Is.Not.EqualTo(new[] { 0, 1, 2, 3, 4, 5, 6, 7 }));
        Assert.That(isContinuousRotation(output), Is.True,
            $"Mapping must be a continuous rotation for seed {seed}");
    }
}
